### ISSUE TITLE
Noob 6: alternative way to solve

### ISSUE THREAD

**Issue by mathiasbockwoldt** [NikolaiMagnussen/UiTHack#2]
Thank you very much for creating the UiTHack2017! I'm looking forward to the next hacking contest!

I read through the writeups and solved most of the challenges in a similar way. But noob 6 is solvable even if one wouldn't have access with another account like noob5 to read out the `/etc/passwd`.

After some less successful other tricks, I tried to have the terminal window very small, only a few lines high. This forces `more` to stay in interactive mode and to not exit. Within `more`, it is possible to open `vim` by pressing `v`. Within `vim`, one can easily open the original `flags.txt` by typing `:e ` and then tabbing through the files. By tabbing, I didn't even have to know, how the file is called beforehand.

**Comment by NikolaiMagnussen** [comment]
Awesome way to solve it as well. If you want to add it to the writeup of Noob 6, just send a pull request such that it will be easier to see.

**Comment by NikolaiMagnussen** [comment]
Closing issue due to no pull request
